#!/bin/zsh
#user must be root to run this
if [ "$EUID" -ne 0 ]
    then echo "Must be root to run this"
    exit 1
fi

#h8 on windows and ntfs
ntfsfix /dev/sda2
mount -o gid=wheel /dev/sda2 /mnt/usb01

