#!/bin/bash

root()
{
    #user must be root to run this
    if [ "$EUID" -ne 0 ]
        then echo "Must be root to run this"
        exit 1
    fi
    if [ -z "$1" ]; then
        printf "specify the network\n"
        exit 1
    fi
}

net_select()
{
    local __res=$1
    local network=''
    #lrz support and start vpn
    #add more options if needed
    if [ "$2" == "uni" ]; then
        #specify lrz or eduroam and start respective services
        printf "uni-network\n"
        network="eduroam"
    elif [ "$2" == "home" ]; then
        printf "home-network\n"
        network="grande"
    elif [ "$2" == "lrz" ]; then
        printf "lrz-network: will start vpn services\n"
        network="lrz"
    elif [ "$2" == "bio" ]; then
        printf "bio\n"
        network="bio"
    elif [ "$2" == "glh" ]; then
        printf "glh\n"
        network="glh"
    elif [ "$2" == "san" ]; then
        printf "san\n"
        network="san"
    elif [ "$2" == "alsa" ]; then
        printf "alsa\n"
        network="alsa"
    else
        printf "no such network\n"
        exit -1
    fi
    eval $__res="'$network'"
}

init()
{
    local interface="wlp3s0"

    ip link set $interface up
    printf "Interface is up.\n"

    #get pid of wpa_supplicant
    wpa_pid="$(ps aux | pgrep wpa)"

    #check if it is running if it is, kill it
    #-n returns if a var is set or not empty string
    if [ -n "$wpa_pid" ]; then
        #echo $wpa_pid
        printf "Wpa_supplicant running on %d\n" $wpa_pid
        printf "killing wpa_suppicant %d\n" $wpa_pid
        kill $wpa_pid
    else
        #let error="cant find wpa process"
        printf "no wpa running\n"
    fi
    #let user chose which script
    #catch errors coming from wpa_supplicant
    printf "starting wpa_suplicant\n"
    wpa_supplicant -i $interface -c /etc/wpa_supplicant/$1.conf

    dhcp_pid="$(ps aux | pgrep dhcpcd)"

    if [ -n "$dhcp_pid" ]; then
        printf "dhcpcd is running on %d\n" $dhcp_pid
    else
        printf "starting dhcpcd on %s\n" $interface
        dhcpcd $interface
    fi

    if [ "$1" = "lrz" ]; then
        printf "starting vpn service...\n"
        vpnc /etc/vpnc/lrz.conf
    fi
}

main()
{
    root $1
    net_select net "$1"
    init $net
    exit 0
}

main "$@"
